init: create module
踩坑点
1. 应该点明type=module，不然会出现在import chalk from 'chalk';的时候提示SyntaxError: Cannot use import statement outside a module
2. chatgpt诊断为尝试使用commonjs，在改写为const chalk = require('chalk');或者添加require = require("esm")(module);后都不行，反而提示chalk必须在esm下运行不然会有ERR_REQUIRE_ESM的报错
3. 应该在npm add以后添加chalk在以来中并安装chalk在pwd下，不然有Error: Cannot find module 'chalk'错误
4. chatgptV4建议改一下package.json加入type
问题解决
好了现在可以保留干净的js文件了

感谢我的js启蒙项目 https://github.com/osmlab/name-suggestion-index/blob/main/scripts/build_index.js